[package]
name = "stdio-inspect"
version = "0.1.0"
authors = ["Dmitriy Belyaev <mail@d-belyaev.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "^1.4.0", features = ["full"] }
